{{- if .Values.extSecret -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.extSecret.name }}
  namespace: {{ .Release.namespace }}
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ .Values.extSecret.secretName }}
  refreshInterval: {{ .Values.extSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-sm-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ .Values.extSecret.name }}
{{- end -}}