{
 "title": "AWS MemoryDB Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "clusterName",
    "query": {}
   },
   {
    "name": "nodeName",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Database Memory Usage Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "$clusterName" },
     "metricName": "DatabaseMemoryUsagePercentage",
     "namespace": "AWS/MemoryDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "FreeableMemory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "$clusterName" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/MemoryDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dimensions": { "ClusterName": "$clusterName" },
     "metricName": "CurrConnections",
     "namespace": "AWS/MemoryDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Current Items",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dimensions": { "ClusterName": "$clusterName" },
     "metricName": "CurrItems",
     "namespace": "AWS/MemoryDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CPUUtilization Precentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "$clusterName" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/MemoryDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "EngineCPUUtilization Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "$clusterName" },
     "metricName": "EngineCPUUtilization",
     "namespace": "AWS/MemoryDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "NetworkPacketsIn",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "dimensions": { "ClusterName": "$clusterName" },
     "metricName": "NetworkPacketsIn",
     "namespace": "AWS/MemoryDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "NetworkPacketsOut",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "dimensions": { "ClusterName": "$clusterName" },
     "metricName": "NetworkPacketsOut",
     "namespace": "AWS/MemoryDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "NetworkBandwidhtInAllownaceExceeded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "targets": [
    {
     "dimensions": { "ClusterName": "$clusterName" },
     "metricName": "NetworkBandwidthInAllowanceExceeded",
     "namespace": "AWS/MemoryDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "NetworkBandwidhtOutAllownaceExceeded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "dimensions": { "ClusterName": "$clusterName" },
     "metricName": "NetworkBandwidthOutAllowanceExceeded",
     "namespace": "AWS/MemoryDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "KeyspaceHits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "dimensions": { "ClusterName": "$clusterName" },
     "metricName": "KeyspaceHits",
     "namespace": "AWS/MemoryDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": " KeyspaceMisses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "dimensions": { "ClusterName": "$clusterName" },
     "metricName": "KeyspaceMisses",
     "namespace": "AWS/MemoryDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "IsPrimary",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "$clusterName", "NodeName": "$nodeName" },
     "metricName": "IsPrimary",
     "namespace": "AWS/MemoryDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}