{
 "title": "Client overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "App loads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(appVersion) (sum_over_time(client_app_loaded_count[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Board operations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum by(appVersion) (sum_over_time(client_board_operation_count[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Purchases",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum by(status) (sum_over_time(client_purchase_completed_count[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Purchases",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(status) (client_purchase_completed_count)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(appVersion) (increase(client_session_duration_count))/3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 10 },
   "targets": [
    {
     "expr": "sum by(action) (sum_over_time(client_errors_count[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active users by country",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "expr": "sum by(country) (increase(client_session_duration_count[$__rate_interval]))/3",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Backend Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (endpoint) (sum_over_time(client_request_duration_count{host='api.traveltowngame.net', endpoint !~'.*00.*'}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "abs(avg by (endpoint) (client_request_duration_average{host='api.traveltowngame.net',  endpoint !~'.*00.*'}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by ( status) (sum_over_time(client_request_duration_count{host='api.traveltowngame.net', endpoint !~'.*00.*', status !~'200|201|202|203|204|205|300|301|302|303'}))",
     "legendFormat": "{{status}}, {{endpoint}}"
    }
   ]
  },
  {
   "title": "Backend error rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(client_request_duration_count{host='api.traveltowngame.net', endpoint !~'.*00.*', status !~'200|201|202|203|204|205|300|301|302|303|304'}))/sum(increase(client_request_duration_count{host='api.traveltowngame.net', endpoint !~'.*00.*'}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}