{
 "title": "Tag diffs and blocked services",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Blocked services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Blocked objects count on beta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(cluster) (changes(blocked_objects_total{cluster=\"tt-prod-beta\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked objects on beta",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "changes(blocked_objects_total{cluster=\"tt-prod-beta\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked objects count on prod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(cluster) (changes(blocked_objects_total{cluster=\"tt-prod-a\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(cluster) (changes(blocked_objects_total{cluster=\"tt-prod-b\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked objects on prod",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "changes(blocked_objects_total{cluster!=\"tt-prod-beta\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Image diff in services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Image diff count: prod-beta & prod-a",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "count by(service_name) (changes(env_tag_diff_total{cluster1=\"tt-prod-beta\", cluster2=\"tt-prod-a\", namespace1=\"prod\", namespace2=\"prod\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Image diff by service: prod-beta & prod-a",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "changes(env_tag_diff_total{cluster1=\"tt-prod-beta\", cluster2=\"tt-prod-a\", namespace1=\"prod\", namespace2=\"prod\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Image diff count: prod-beta & prod-b",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "count by(service_name) (changes(env_tag_diff_total{cluster1=\"tt-prod-beta\", cluster2=\"tt-prod-b\", namespace1=\"prod\", namespace2=\"prod\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Image diff by service: prod-beta & prod-b",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "changes(env_tag_diff_total{cluster1=\"tt-prod-beta\", cluster2=\"tt-prod-b\", namespace1=\"prod\", namespace2=\"prod\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Image diff count: prod-a & prod-b",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "count by(service_name) (changes(env_tag_diff_total{cluster1=\"tt-prod-a\", cluster2=\"tt-prod-b\", namespace1=\"prod\", namespace2=\"prod\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Image diff by service: prod-a & prod-b",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "changes(env_tag_diff_total{cluster1=\"tt-prod-a\", cluster2=\"tt-prod-b\", namespace1=\"prod\", namespace2=\"prod\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Image diff count: stage & prod-b",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "count by(service_name) (changes(env_tag_diff_total{cluster1=\"ma-tt-stage\", cluster2=\"tt-prod-b\", namespace1=\"stage\", namespace2=\"prod\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Image diff by service: stage & prod-b",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "changes(env_tag_diff_total{cluster1=\"ma-tt-stage\", cluster2=\"tt-prod-b\", namespace1=\"stage\", namespace2=\"prod\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}