{
 "title": "CI data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Build",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "AVG workflow times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "avg(workflow_time{workflow_name=\"CI/CD For Dev\", job=\"build-and-push\"})",
       "legendFormat": "Dev"
      },
      {
       "expr": "avg(workflow_time{workflow_name=\"CI/CD for master\", job=\"build-and-push\"})",
       "legendFormat": "beta"
      }
     ]
    },
    {
     "title": "Workflow times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 1 },
     "targets": [
      {
       "expr": "workflow_time{workflow_name=\"CI/CD For Dev\", job=\"build-and-push\"}",
       "legendFormat": "{{workflow_name}} - {{job}} - {{run_url}}"
      },
      {
       "expr": "workflow_time{workflow_name=\"CI/CD for master\", job=\"build-and-push\"}",
       "legendFormat": "{{workflow_name}} - {{job}} - {{run_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NPM installs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of npm install",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(pr_run_npm_install_total{status=\"success\"})",
       "legendFormat": "Number of success npm install"
      },
      {
       "expr": "sum(pr_run_npm_install_total{status=\"failure\"})",
       "legendFormat": "Number of failed npm install"
      }
     ]
    },
    {
     "title": "NPM installs (success and failure)",
     "type": "table",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 2 },
     "targets": [
      { "expr": "pr_run_npm_install_total", "legendFormat": "{{label_name}}" }
     ]
    },
    {
     "title": "AVG npm install time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "avg(pr_run_npm_install_time_sum)",
       "legendFormat": "npm install time"
      }
     ]
    }
   ]
  },
  {
   "title": "NPM test",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of npm tests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(pr_run_npm_test_total{status=\"success\"})",
       "legendFormat": "Number of success npm tests"
      },
      {
       "expr": "sum(pr_run_npm_test_total{status=\"failure\"})",
       "legendFormat": "Number of failed npm tests"
      }
     ]
    },
    {
     "title": "NPM tests (success and failure)",
     "type": "table",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 3 },
     "targets": [
      { "expr": "pr_run_npm_test_total", "legendFormat": "{{label_name}}" }
     ]
    },
    {
     "title": "AVG npm tests time (in seconds)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "targets": [
      { "expr": "avg(pr_run_npm_test_time_sum)", "legendFormat": "npm install time" }
     ]
    },
    {
     "title": "AVG workflow times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "avg(workflow_time{workflow_name=\"PR checks\", job=\"npm-test-check\"})",
       "legendFormat": "npm-test-check"
      }
     ]
    },
    {
     "title": "Workflow times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 18 },
     "targets": [
      {
       "expr": "workflow_time{workflow_name=\"PR checks\", job=\"npm-test-check\"}",
       "legendFormat": "{{workflow_name}} - {{job}} - {{run_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dep test",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of dep tests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum(pr_run_dep_check_total{status=\"success\"})",
       "legendFormat": "Number of success dependency checks"
      },
      {
       "expr": "sum(pr_run_dep_check_total{status=\"failure\"})",
       "legendFormat": "Number of failed dependency checks"
      }
     ]
    },
    {
     "title": "Dep tests (success and failure)",
     "type": "table",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 4 },
     "targets": [
      { "expr": "pr_run_dep_check_total", "legendFormat": "{{label_name}}" }
     ]
    },
    {
     "title": "AVG dep check time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "targets": [
      { "expr": "avg(pr_run_dep_check_time_sum)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "AVG workflow times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "avg(workflow_time{workflow_name=\"PR checks\", job=\"npm-deps-check\"})",
       "legendFormat": "npm-deps-check"
      }
     ]
    },
    {
     "title": "Workflow times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 21 },
     "targets": [
      {
       "expr": "workflow_time{workflow_name=\"PR checks\", job=\"npm-deps-check\"}",
       "legendFormat": "{{workflow_name}} - {{job}} - {{run_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JSON validate test",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of json validate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum(pr_run_json_check_total{status=\"success\"})",
       "legendFormat": "Number of success npm install"
      },
      {
       "expr": "sum(pr_run_json_check_total{status=\"failure\"})",
       "legendFormat": "Number of failed npm install"
      }
     ]
    },
    {
     "title": "JSON validate (success and failure)",
     "type": "table",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 20 },
     "targets": [
      { "expr": "pr_run_json_check_total", "legendFormat": "{{label_name}}" }
     ]
    },
    {
     "title": "AVG json validate time ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "avg(pr_run_json_check_time_sum)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AVG workflow times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "avg(workflow_time{workflow_name=\"PR checks\", job=\"json-status-check\"})",
       "legendFormat": "json-status-check"
      }
     ]
    },
    {
     "title": "Workflow times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 37 },
     "targets": [
      {
       "expr": "workflow_time{workflow_name=\"PR checks\", job=\"json-status-check\"}",
       "legendFormat": "{{workflow_name}} - {{job}} - {{run_url}}"
      }
     ]
    }
   ]
  }
 ]
}