{
 "title": "After deployment steps",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Prod images added to list", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prod images added to list",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum_over_time(add_prod_image_to_list_total[$__interval])",
     "legendFormat": "{{service_name}}:{{prod_tag}}"
    },
    {
     "expr": "count(count_over_time(workflow_time {workflow_name=\"Deploy from beta to prod\"}))",
     "legendFormat": "deployment to prod"
    }
   ]
  },
  {
   "title": "Prod images added to list",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum_over_time(add_prod_image_to_list_total[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Merge down", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Success / Failed merge down",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (sum_over_time(merge_down_total{status=\"success\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(status) (sum_over_time(merge_down_total{status=\"failure\"}[$__range]))",
     "legendFormat": "merge conflict"
    }
   ]
  },
  {
   "title": "Success / Failed merge down ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 10 },
   "targets": [
    {
     "expr": "sum by(status) (sum_over_time(merge_down_total{status=\"success\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(status) (sum_over_time(merge_down_total{status=\"failure\"}[$__interval]))",
     "legendFormat": "merge conflict"
    }
   ]
  },
  {
   "title": "Success / Failed merge down list",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "label_replace(changes(merge_down_total[$__interval]), \"status\", \"merge conflict\", \"status\", \"failure\")",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Deploy on all envs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Success / Failed deploy on all envs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (sum_over_time(deploy_on_all_envs_total{status=\"success\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(status) (sum_over_time(deploy_on_all_envs_total{status=\"failure\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deploy on all envs Success / Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 19 },
   "targets": [
    {
     "expr": "sum by(status) (sum_over_time(deploy_on_all_envs_total{status=\"success\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(status) (sum_over_time(deploy_on_all_envs_total{status=\"failure\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success / Failed deploy on all envs list",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "changes(deploy_on_all_envs_total[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}