{
 "title": "Devops bot operations",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "helper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total devops issue created",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 109 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(changes(slack_bot_get_devops_help_total[$__interval])[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of issues by day",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 6, "y": 109 },
     "targets": [
      {
       "expr": "sum(sum(slack_bot_get_devops_help_total))",
       "legendFormat": "Num of issues"
      }
     ]
    },
    {
     "title": "Issues opened over time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 109 },
     "targets": [
      {
       "expr": "slack_bot_get_devops_help_total",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "Total docs opened",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 118 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(changes(slack_bot_helpers_total[$__interval])[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Docs opened over time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 118 },
     "targets": [
      {
       "expr": "slack_bot_helpers_total",
       "legendFormat": "{{ view_opened}} - {{username}}"
      }
     ]
    },
    {
     "title": "Number of issues by user",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 127 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(changes(slack_bot_get_devops_help_total[$__interval])) by (username)",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "Number of docs opened by user",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 139 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(changes(slack_bot_helpers_total[$__interval])) by (username)",
       "legendFormat": "{{username}}"
      }
     ]
    }
   ]
  },
  {
   "title": "slack bot actions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "sum(slack_bot_operations_total[$__interval])[$__range]",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Operations list",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "changes(slack_bot_operations_total[$__interval])",
       "legendFormat": "{{operation}} - {{username}}"
      }
     ]
    },
    {
     "title": "Operations usage",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "sum(changes(slack_bot_operations_total[$__interval])[$__range]) by (operation)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Operations by user",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "targets": [
      {
       "expr": "changes(slack_bot_operations_total[$__interval])",
       "legendFormat": "{{username}}/{{category}}/{{operation}}"
      }
     ]
    },
    {
     "title": "Operations usage by operation",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 14, "x": 5, "y": 65 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(slack_bot_operations_total{}) by (operation)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bot top users",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 73 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(changes(slack_bot_operations_total[$__interval])) by (username)",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "Bot top operations",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(changes(slack_bot_operations_total[$__interval])) by (operation)",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "Bot total usage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 96 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(changes(slack_bot_operations_total[$__interval]))",
       "legendFormat": "{{username}}"
      }
     ]
    }
   ]
  },
  { "title": "HeartBeat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Slackbot table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "expr": "bots_heartbeat_total[30d]", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bots by version",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(release_version)(bots_heartbeat_total{release_version!=\"\"})[30d]",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "Slackbot Clients",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(bot_name) (bots_heartbeat_total)[30d]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum by provider",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (provider)(bots_heartbeat_total{provider!=\"\"})[30d]",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}