{
 "title": "Nightly runs",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Auto destroy OD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Auto destroy ODs status count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(status) (changes(od_destroyment_total{called_by=\"destroy_old_ods_action\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Auto destroy ODs status / in time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 5, "y": 10 },
     "targets": [
      {
       "expr": "count by(status) (changes(od_destroyment_total{called_by=\"destroy_old_ods_action\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Auto destroy ODs list",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "changes(od_destroyment_total{called_by=\"destroy_old_ods_action\"}[$__interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Notifications ",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(status) (changes(auto_destroy_od_notification_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Notifications / days remains",
     "type": "stat",
     "gridPos": { "h": 8, "w": 7, "x": 5, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(days_remains) (changes(auto_destroy_od_notification_total[$__range]))",
       "legendFormat": "{{days_remains}} days"
      }
     ]
    },
    {
     "title": "Notifications list",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "changes(auto_destroy_od_notification_total[$__interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Scale down OD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scale down ODs status count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(status) (changes(od_scaledown_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scale down ODs / in time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 5, "y": 2 },
     "targets": [
      {
       "expr": "count by(status) (changes(od_scaledown_total[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scale down ODs list",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "changes(od_scaledown_total{status=\"success\"}[$__interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Package updates notifier",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Package update's notifier heartbeat",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(changes(devops_heartbeat_total {job=\"package_updates_notifier_action\"}[$__interval])[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scale down ODs list",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 3 },
     "targets": [
      {
       "expr": "changes(devops_heartbeat_total{job=\"package_updates_notifier_action\"}[$__interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}