{
 "title": "OD data",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Od Amount",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current number of od's (stage)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 5, "x": 1, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "od_amount{cluster=\"ma-tt-stage\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of od's over time (stage)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 5, "x": 6, "y": 1 },
     "targets": [
      {
       "expr": "od_amount{cluster=\"ma-tt-stage\"}",
       "legendFormat": "Number od od envs"
      }
     ]
    },
    {
     "title": "Current number of od's (rc)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 5, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "od_amount{cluster=\"tt-rc\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of od's over time (rc)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 5, "x": 17, "y": 1 },
     "targets": [
      {
       "expr": "od_amount{cluster=\"tt-rc\"}",
       "legendFormat": "Number od od envs"
      }
     ]
    }
   ]
  },
  {
   "title": "Od creation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of od envs created",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(od_creation_total{status=\"success\"})",
       "legendFormat": "Number od envs created"
      }
     ]
    },
    {
     "title": "Od envs created",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 13 },
     "targets": [
      {
       "expr": "od_creation_total{status=\"success\"}",
       "legendFormat": "od_name: {{od_name}} owner: {{owner}} url: {{url}}"
      }
     ]
    },
    {
     "title": "Od creation runs (success and failure)",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 13 },
     "targets": [
      { "expr": "od_creation_total", "legendFormat": "{{label_name}}" }
     ]
    },
    {
     "title": "Number of od envs failed to create",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 13 },
     "targets": [
      {
       "expr": "sum(od_creation_total{status=\"failure\"})",
       "legendFormat": "Number od envs failed to create"
      }
     ]
    },
    {
     "title": "AVG od creation time (in minutes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "avg((od_creation_time_sum > 30)/60)",
       "legendFormat": "od creation time"
      }
     ]
    },
    {
     "title": "od creation time (in minutes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "(od_creation_time_sum > 30)/60",
       "legendFormat": "od_name: {{od_name}} owner: {{owner}} url: {{url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Od destroyment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of od envs destroyed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum(od_destroyment_total { status=\"success\"})",
       "legendFormat": "Number od envs destroyed"
      }
     ]
    },
    {
     "title": "Od envs destroyed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 31 },
     "targets": [
      {
       "expr": "od_destroyment_total { status=\"success\"}",
       "legendFormat": "od_name: {{od_name}} owner: {{owner}} url: {{url}}"
      }
     ]
    },
    {
     "title": "Od destroyment runs (success and failure)",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 31 },
     "targets": [
      { "expr": "od_destroyment_total", "legendFormat": "{{label_name}}" }
     ]
    },
    {
     "title": "Number of od envs failed to destroy",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 31 },
     "targets": [
      {
       "expr": "sum(od_destroyment_total { status=\"failure\"})",
       "legendFormat": "Number od envs failed to destroy"
      }
     ]
    },
    {
     "title": "AVG od destroyment time (in minutes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "avg((od_destroyment_time_sum > 5)/60)",
       "legendFormat": "od destroyment time"
      }
     ]
    },
    {
     "title": "od destroyment time (in minutes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "targets": [
      {
       "expr": "(od_destroyment_time_sum >5)/60",
       "legendFormat": "od_name: {{od_name}} owner: {{owner}} url: {{url}}"
      }
     ]
    },
    {
     "title": "Deleted od envs image tags",
     "type": "logs",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
     "targets": [
      { "expr": "od_image_tags_info", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}