{
 "title": "CD data",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All envs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of  deployments (All envs)",
     "type": "gauge",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "count(count(last_over_time(deploy_service_total)) by (metric_id))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of successful deployments (All envs)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 7, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "count(count(last_over_time(deploy_service_total {status=\"success\"})) by (metric_id))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "rate of failed deployments (All envs)",
     "type": "gauge",
     "gridPos": { "h": 12, "w": 9, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(sum(deploy_service_total{status=\"failure\"}[$__range]) / sum(deploy_service_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of  failed deployments (All envs)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 7, "x": 8, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "count(count(last_over_time(deploy_service_total {status=\"failure\"})) by (metric_id))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "succesful runs (All envs)",
     "type": "table",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "deploy_service_total{status=\"success\"}",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "failed runs (All envs)",
     "type": "table",
     "gridPos": { "h": 10, "w": 13, "x": 11, "y": 13 },
     "targets": [
      {
       "expr": "deploy_service_total{status=\"failure\"}",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Average workflow times (All envs)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "avg(workflow_time{workflow_name=\"CI/CD For Dev\", job=\"deploy\"})",
       "legendFormat": "CI/CD For Dev"
      },
      {
       "expr": "avg(workflow_time{workflow_name=\"CI/CD for master\", job=\"deploy\"})",
       "legendFormat": "CI/CD for master"
      },
      {
       "expr": "avg(workflow_time{workflow_name=\"Deploy from beta to prod\"})",
       "legendFormat": "Deploy from beta to prod"
      }
     ]
    },
    {
     "title": "Workflow times (All envs)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 23 },
     "targets": [
      {
       "expr": "workflow_time{workflow_name=\"CI/CD For Dev\", job=\"deploy\"}",
       "legendFormat": "{{workflow_name}} - {{run_url}}"
      },
      {
       "expr": "workflow_time{workflow_name=\"CI/CD for master\", job=\"deploy\"}",
       "legendFormat": "{{workflow_name}} - {{run_url}}"
      },
      {
       "expr": "workflow_time{workflow_name=\"Deploy from beta to prod\"}",
       "legendFormat": "{{workflow_name}} - {{run_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of succesful and failed deployments",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(deploy_service_total {env=\"stage\",status=\"success\"})",
       "legendFormat": "success"
      },
      {
       "expr": "sum(deploy_service_total {env=\"stage\",status=\"failure\"})",
       "legendFormat": "failure"
      }
     ]
    },
    {
     "title": "Percentage of failed deployments in specific time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 9, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(sum(deploy_service_total{env=\"stage\", status=\"failure\"}) / sum(deploy_service_total{env=\"stage\"}))",
       "legendFormat": "failure"
      }
     ]
    },
    {
     "title": "rate of failed deployments",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(sum(deploy_service_total{env=\"stage\", status=\"failure\"}[$__range]) / sum(deploy_service_total{env=\"stage\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of successful deployments",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "count(count(last_over_time(deploy_service_total{env=\"stage\", status=\"success\"})) by (metric_id))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of failed deployments",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "count(count(last_over_time(deploy_service_total{env=\"stage\", status=\"failure\"})) by (metric_id))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "succesful runs",
     "type": "table",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "deploy_service_total{env=\"stage\", status=\"success\"}",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "failed runs",
     "type": "table",
     "gridPos": { "h": 10, "w": 13, "x": 11, "y": 14 },
     "targets": [
      {
       "expr": "deploy_service_total { env=\"stage\", status= \"failure\"}  ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average workflow times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "avg(workflow_time{workflow_name=\"CI/CD For Dev\", job=\"deploy\"})",
       "legendFormat": "CI/CD For Dev"
      }
     ]
    },
    {
     "title": "Workflow times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 24 },
     "targets": [
      {
       "expr": "workflow_time{workflow_name=\"CI/CD For Dev\", job=\"deploy\"}",
       "legendFormat": "{{workflow_name}} - {{run_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Beta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of succesful and failed deployments",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(deploy_service_total {env=\"beta\",status=\"success\"})",
       "legendFormat": "success"
      },
      {
       "expr": "sum(deploy_service_total {env=\"beta\",status=\"failure\"})",
       "legendFormat": "failure"
      }
     ]
    },
    {
     "title": "Percentage of failed deployments in specific time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 9, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(sum(deploy_service_total{env=\"beta\", status=\"failure\"}) / sum(deploy_service_total{env=\"beta\"}))",
       "legendFormat": "failure"
      }
     ]
    },
    {
     "title": "rate of failed deployments",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(sum(deploy_service_total{env=\"beta\", status=\"failure\"}[$__range]) / sum(deploy_service_total{env=\"beta\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of successful deployments",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "count(count(last_over_time(deploy_service_total{env=\"beta\", status=\"success\"})) by (metric_id))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of failed deployments",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "count(count(last_over_time(deploy_service_total{env=\"beta\", status=\"failure\"})) by (metric_id))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "succesful runs",
     "type": "table",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "deploy_service_total { env=\"beta\", status= \"success\"}  ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed runs",
     "type": "table",
     "gridPos": { "h": 10, "w": 13, "x": 11, "y": 15 },
     "targets": [
      {
       "expr": "deploy_service_total {env=\"beta\", status= \"failure\"}  ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average workflow times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "avg(workflow_time{workflow_name=\"CI/CD for master\", job=\"deploy\"})",
       "legendFormat": "CI/CD for master"
      }
     ]
    },
    {
     "title": "Workflow times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 25 },
     "targets": [
      {
       "expr": "workflow_time{workflow_name=\"CI/CD for master\", job=\"deploy\"}",
       "legendFormat": "{{workflow_name}} - {{run_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Prod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of succesful and failed deployments",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum(deploy_service_total {env=\"prod\",status=\"success\"})",
       "legendFormat": "success"
      },
      {
       "expr": "sum(deploy_service_total {env=\"prod\",status=\"failure\"})",
       "legendFormat": "failure"
      }
     ]
    },
    {
     "title": "Percentage of failed deployments in specific time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 9, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(sum(deploy_service_total{env=\"prod\", status=\"failure\"}) / sum(deploy_service_total{env=\"prod\"}))",
       "legendFormat": "failure"
      }
     ]
    },
    {
     "title": "rate of failed deployments",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(sum(deploy_service_total{env=\"prod\", status=\"failure\"}[$__range]) / sum(deploy_service_total{env=\"prod\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of successful deployments",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "count(count(last_over_time(deploy_service_total{env=\"prod\", status=\"success\"})) by (metric_id))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of failed deployments",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "count(count(last_over_time(deploy_service_total{env=\"prod\", status=\"failure\"})) by (metric_id))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "succesful runs",
     "type": "table",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "deploy_service_total { env=\"prod\", status= \"success\"}  ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "failed runs",
     "type": "table",
     "gridPos": { "h": 10, "w": 13, "x": 11, "y": 16 },
     "targets": [
      {
       "expr": "deploy_service_total { env=\"prod\", status= \"failure\"}  ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average workflow times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "avg(workflow_time{workflow_name=\"Deploy from beta to prod\"})",
       "legendFormat": "Deploy from beta to prod"
      }
     ]
    },
    {
     "title": "Workflow times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 26 },
     "targets": [
      {
       "expr": "workflow_time{workflow_name=\"Deploy from beta to prod\"}",
       "legendFormat": "{{workflow_name}} - {{run_url}}"
      }
     ]
    }
   ]
  }
 ]
}