{
 "title": "CI/CD times",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Stage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "AVG deploy_service func time on stage [Full CI/CD]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "avg(deploy_service_time_sum{env=\"stage\"} > 30)",
       "legendFormat": "AVG deploy service on stage time"
      }
     ]
    },
    {
     "title": "deploy_service func time on stage [Full CI/CD]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "(deploy_service_time_sum{env=\"stage\"} > 30)",
       "legendFormat": "metric_id: {{metric_id}} url: {{url}}"
      }
     ]
    },
    {
     "title": "AVG create_od func time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "avg((od_creation_time_sum > 30))",
       "legendFormat": "AVG od creation time"
      }
     ]
    },
    {
     "title": "create_od func time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "(od_creation_time_sum > 30)",
       "legendFormat": "metric_id: {{metric_id}} url: {{url}}"
      }
     ]
    },
    {
     "title": "AVG workflow times [CI only]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "avg(workflow_time{workflow_name=\"CI/CD For Dev\", job=\"build-and-push\"})",
       "legendFormat": "CI/CD For Dev"
      }
     ]
    },
    {
     "title": "Workflow times [CI only]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "workflow_time{workflow_name=\"CI/CD For Dev\", job=\"build-and-push\"}",
       "legendFormat": "{{workflow_name}} - {{run_url}}"
      }
     ]
    },
    {
     "title": "AVG workflow times [Full CI/CD]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "avg(workflow_time{workflow_name=\"CI/CD For Dev\", job=\"deploy\"})",
       "legendFormat": "CI/CD For Dev"
      }
     ]
    },
    {
     "title": "Workflow times [Full CD/CD]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "workflow_time{workflow_name=\"CI/CD For Dev\", job=\"deploy\"}",
       "legendFormat": "{{workflow_name}} - {{run_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Beta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "AVG deploy_service func time on beta [Full CI/CD]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "avg(deploy_service_time_sum{env=\"beta\"} > 30)",
       "legendFormat": "AVG deploy service on beta time"
      }
     ]
    },
    {
     "title": "deploy_service func time on beta [Full CI/CD]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "(deploy_service_time_sum{env=\"beta\"} > 30)",
       "legendFormat": "metric_id: {{metric_id}} url: {{url}}"
      }
     ]
    },
    {
     "title": "AVG workflow times [CI only]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "avg(workflow_time{workflow_name=\"CI/CD for master\", job=\"build-and-push\"})",
       "legendFormat": "CI/CD For beta"
      }
     ]
    },
    {
     "title": "Workflow times [CI only]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "workflow_time{workflow_name=\"CI/CD for master\", job=\"build-and-push\"}",
       "legendFormat": "CI/CD for beta - {{run_url}}"
      }
     ]
    },
    {
     "title": "AVG workflow times [Full CI/CD]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "avg(workflow_time{workflow_name=\"CI/CD for master\", job=\"deploy\"})",
       "legendFormat": "CI/CD For Dev"
      }
     ]
    },
    {
     "title": "Workflow times [Full CD/CD]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "workflow_time{workflow_name=\"CI/CD for master\", job=\"deploy\"}",
       "legendFormat": "{{workflow_name}} - {{run_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Prod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "AVG deploy_service func time on prod [CD only]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "avg(deploy_service_time_sum{env=\"prod\"} > 30) / 60",
       "legendFormat": "AVG deploy service on prod time"
      }
     ]
    },
    {
     "title": "deploy_service func time on prod [CD only]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "(deploy_service_time_sum{env=\"prod\"} > 30)",
       "legendFormat": "metric_id: {{metric_id}} url: {{url}}"
      }
     ]
    },
    {
     "title": "AVG workflow times [Deploy from beta]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "avg(workflow_time{workflow_name=\"Deploy from beta to prod\"})",
       "legendFormat": "Deploy from beta to prod"
      }
     ]
    },
    {
     "title": "Workflow times [Deploy from beta]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "workflow_time{workflow_name=\"Deploy from beta to prod\"}",
       "legendFormat": "Deploy from beta to prod - {{run_url}}"
      }
     ]
    }
   ]
  }
 ]
}